spring.application.name=auth-service

server.port = 8010

#spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=QAPDBS;encrypt=true;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=AI_CHATBOT;encrypt=true;trustServerCertificate=true

spring.datasource.username=admin_qa
spring.datasource.password=srb@1029
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.user.name = rizwan
#spring.security.user.password=srb
# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# IMPORTANT (fix hostname issue)
eureka.instance.prefer-ip-address=true